--- #YAML:1.0
name:               DBIx-VersionedDDL
version:            0.02
abstract:           Upgrade and downgrade database schemas to a specified version.
author:
    - Dan Horne <dan.horne@redbone.co.nz>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBD::SQLite:  0
    DBI:          0
    Moose:        0
    Pod::Usage:   0
    Test::More:   0
    Text::CSV:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
