---
abstract: 'Upgrade and downgrade database schemas to a specified version.'
author:
  - 'Dan Horne <dan.horne@redbone.co.nz>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-VersionedDDL
no_index:
  directory:
    - t
    - inc
requires:
  DBD::SQLite: 0
  DBI: 0
  Moose: 0
  MooseX::Attribute::ENV: 0
  MooseX::Object::Pluggable: 0
  Pod::Usage: 0
  Test::More: 0
  Text::CSV: 0
version: 0.17
